server:
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
  flyway:
    enabled: true
login:
  base-url: https://api.puzzleshare.site
  redirect-url: https://puzzleshare.site/login/redirect
