spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379