spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

login:
  base-url: https://container-service-1.9sjrmz3hsgdvw.ap-northeast-2.cs.amazonlightsail.com
  redirect-url: http://localhost:5173/login/redirect