spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    clean-on-validation-error: true
    enabled: true
  data:
    redis:
      # host: TODO 레디스 서버
      port: 6379